### ISSUE TITLE
PyPI Submission

### ISSUE THREAD

**Issue by jaedoucette** [PrincetonUniversity/blocklint#7]
Blocklint is not present in PyPI. 

When using blocklint as part of a CI/CD pipeline for larger software projects, it would be nice to be able to install specific versions and to rely on the reachability of a PyPI cache rather than public github, which may not always be available in corporate environments. 

This problem would be solved by publishing a version of blocklint to PyPI. 

I can assist with this if it would be helpful.

**Comment by troycomi** [comment]
Excellent point.  I'll try to address this before the new year.

**Comment by troycomi** [comment]
I think this is done, but I don't have much experience with pypi so let me know if something is broken!

**Comment by jaedoucette** [comment]
@troycomi Thanks! 

Blocklint is now available in PyPI, but only as a package and not as a module. I'll make a PR to add support for invoking it as a module.
